# ------------------------------------------------------------------
version: '3.8'
services:
  # 1. POSTGRESQL (Database - Lokal Konteyner)
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: rag_user
      POSTGRES_PASSWORD: raguser123
      POSTGRES_DB: rag_history_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # 2. FASTAPI (Application Server)
  rag-fastapi-service:
    build: . # Dockerfile-dan istifadə edərək şəkli qur
    container_name: rag-fastapi-service
    ports:
      - "8000:8000"
    env_file:
      - .env # Bütün dəyişənləri konteynerə ötür (o cümlədən Managed OpenSearch URL-i)
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
# ------------------------------------------------------------------